### ISSUE TITLE
Add yarn

### ISSUE THREAD

**Issue by emirotin** [balena-io-modules/open-balena-base#22]
Can we add `yarn` here to make use of it in all of our projects? Or should it go to some of the downstream images?

The command would be `npm i -g yarn`

**Comment by hedss** [comment]
@Page- @shaunmulligan @lekkas I think this is worth closing, `yarn`'s used in the UI and Admin, but we now have `package-lock.json` for the other backend components. If we're not closing it, we should switch wholesale to `yarn`.
